"""added context_summaries column to IdeaSession

Revision ID: c9b0f76a17b3
Revises: 6c8f7ba441df
Create Date: 2025-07-01 20:38:57.904818+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9b0f76a17b3'
down_revision: Union[str, Sequence[str], None] = '6c8f7ba441df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea_sessions', sa.Column('context_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('idea_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('idea_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('idea_sessions_user_id_fkey'), 'idea_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'idea_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'idea_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('idea_sessions_user_id_fkey'), 'idea_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('idea_sessions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('idea_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('idea_sessions', 'context_summaries')
    # ### end Alembic commands ###
