"""Add spec_json to idea_sessions

Revision ID: 6c8f7ba441df
Revises: 84c0aef77e1c
Create Date: 2025-06-30 20:24:04.919584+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c8f7ba441df'
down_revision: Union[str, Sequence[str], None] = '84c0aef77e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea_sessions', sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idea_sessions', 'spec_json')
    # ### end Alembic commands ###
